name: Deploy to cents_be_drycleaning
on:
  push:
    branches:
      - feature/dry-cleaning

jobs:
  deploy_drycleaning:
    if : endsWith(github.ref, '/feature/dry-cleaning')
    uses: make-cents/CentsBE/.github/workflows/deploy_template.yml@feature/dry-cleaning
    name: Deploy with Code Deploy
    with:
      application_name: 'cents-drycleaning'
      deployment_group_name: 'cents-drycleaning-dg'
      iam_role_name: 'deploy-cents-be-dev'
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
