name: Deploy to cents_be_preprod
on:
  push:
    branches:
      - pre-prod

jobs:
  deploy_preprod:
    if : endsWith(github.ref, '/pre-prod')
    uses: make-cents/CentsBE/.github/workflows/deploy_template.yml@pre-prod
    name: Deploy with Code Deploy
    with:
      application_name: 'cents-preprod'
      deployment_group_name: 'cents-preprod-dg'
      iam_role_name: 'deploy-cents-be-preprod'
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
