const router = require('express').Router();

const home = require('./home');
const signIn = require('./signIn');
const payment = require('./payment');
const customers = require('./customers');
const washAndFold = require('./washAndFold');
const inventory = require('./inventory');
const tasks = require('./tasks');
const scandit = require('./scandit');
const tokenAuth = require('../../middlewares/employeeTabAuth');
const promotions = require('./promotions');
const esd = require('./esd');
const cci = require('./cci');
const delivery = require('./delivery');
const printer = require('./printer');
const orders = require('./orders');
const scaleDevice = require('./scaleDevice');
const cashManagement = require('./cashManagement');
const reports = require('./reports');
const teamMembers = require('./teamMembers');
const machines = require('./machines');
const laundroworks = require('./laundroworks');
const bagNoteTags = require('./bagNoteTags');
const tax = require('./tax');
const spyderWash = require('./spyderWash');
const notifications = require('./notifications');

router.use('/sign-in', signIn);
router.use('/home', tokenAuth, home);
router.use('/payment', tokenAuth, payment);
router.use('/customers', tokenAuth, customers);
router.use('/wash-and-fold', tokenAuth, washAndFold);
router.use('/inventory', tokenAuth, inventory);
router.get('/scandit', tokenAuth, scandit);
router.use('/promotions', tokenAuth, promotions);
router.use('/tasks', tokenAuth, tasks);
router.use('/esd', tokenAuth, esd);
router.use('/cci', tokenAuth, cci);
router.use('/delivery', tokenAuth, delivery);
router.use('/printer', tokenAuth, printer);
router.use('/orders', tokenAuth, orders);
router.use('/scale-device', tokenAuth, scaleDevice);
router.use('/cash-management', tokenAuth, cashManagement);
router.use('/reports', tokenAuth, reports);
router.use('/team-members', tokenAuth, teamMembers);
router.use('/machines', tokenAuth, machines);
router.use('/laundroworks', tokenAuth, laundroworks);
router.use('/bag-note-tags', tokenAuth, bagNoteTags);
router.use('/tax', tokenAuth, tax);
router.use('/spyder-wash', tokenAuth, spyderWash);
router.use('/notifications', tokenAuth, notifications);

module.exports = exports = router;
