version: '3'

services:
    main-app:
        build: .
        entrypoint: |
            ${MAIN_APP_CMD}
        ports:
            - ${PORT}:${PORT}
            - '9778:9778'
        environment:
            DB_HOST: postgres
            REDIS_URL: redis://redis:6379/0
            MONGODB_URL: mongodb://mongodb:27017
        volumes:
            - .:/app
            - app-node_modules:/app/node_modules/


volumes:
  app-node_modules:
    driver: local
