name: Deploy to drycleaning
on:
  push:
    branches:
      - feature/dry-cleaning

jobs:
  deploy_preprod:
    if : endsWith(github.ref, '/feature/dry-cleaning')
    uses: make-cents/CentsFE/.github/workflows/deploy_template.yml@feature/dry-cleaning
    name: Deploy to dry-cleaning
    with:
      deployment_bucket_name: 'cents-bo-dev-product-epic'
      iam_role_name: 'deploy-bo-drycleaning'
      env_secret_name: 'drycleaning/bo/env'
      stripe_secret_name: 'dev/react_app/stripe_key'
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      cfd_id: ${{ secrets.DRYCLEANING_CLOUDFRONT_DISTRO_ID }}
