version: 0.2

phases:
  install: 
    commands:
      - yarn
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'

  base-directory: ./build