const windowSelectionActions = {
  INIT: "INIT",
  API_FAILED: "API_FAILED",
  API_STARTED: "API_STARTED",
  SET_CURRENT_TAB: "SET_CURRENT_TAB",
  SET_SELECTED_DATE: "SET_SELECTED_DATE",
  SET_UBER_AUTH_TOKEN: "SET_UBER_AUTH_TOKEN",
  ESTIMATE_CALL_FAILED: "ESTIMATE_CALL_FAILED",
  SET_DOORDASH_ESTIMATE: "SET_DOORDASH_ESTIMATE",
  ESTIMATE_CALL_STARTED: "ESTIMATE_CALL_STARTED",
  TOGGLE_IN_STORE_PICKUP: "TOGGLE_IN_STORE_PICKUP",
  SET_SELECTED_TIME_WINDOWS: "SET_SELECTED_TIME_WINDOWS",
  SET_UBER_ESTIMATE_AND_TIME_WINDOW: "SET_UBER_ESTIMATE_AND_TIME_WINDOW",
  TOGGLE_PICKUP_AND_DELIVERY_WINDOWS: "TOGGLE_PICKUP_AND_DELIVERY_WINDOWS",
  UPDATE_RETURN_METHOD: "UPDATE_RETURN_METHOD",
  TOGGLE_TURNAROUND_TIME_POPUP: "TOGGLE_TURNAROUND_TIME_POPUP",
  SET_IS_PICKUP: "SET_IS_PICKUP",
};

export default windowSelectionActions;
