name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BASE_URL: http://localhost:3001/api/v1/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - name: yarn install, lint and test
        run: |
          yarn install
          yarn lint
          yarn test --watchAll=false
