name: Deploy to epic2
on:
  push:
    branches:
      - feature/tiered-pricing

jobs:
  deploy_epic2:
    if : endsWith(github.ref, '/feature/tiered-pricing')
    uses: make-cents/Cents_LiveLink/.github/workflows/deploy_template.yml@feature/tiered-pricing
    name: Deploy to epic2
    with:
      deployment_bucket_name: 'epic2-livelink'
      iam_role_name: 'deploy-live-link-epic2'
      env_secret_name: 'epic2/live_link/env'
      stripe_secret_name: 'dev/react_app/stripe_key'
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      cfd_id: ${{ secrets.EPIC2_CLOUDFRONT_DISTRO_ID }}
