name: Deploy to preprod
on:
  push:
    branches:
      - pre-prod

jobs:
  deploy_preprod:
    if : endsWith(github.ref, '/pre-prod')
    uses: make-cents/Cents_LiveLink/.github/workflows/deploy_template.yml@pre-prod
    name: Deploy to preprod
    with:
      deployment_bucket_name: 'live-link-pre-prod-fe'
      iam_role_name: 'deploy-live-link-preprod'
      env_secret_name: 'preprod/live_link/env'
      stripe_secret_name: 'prod/react_app/stripe_key'
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      cfd_id: ${{ secrets.PREPROD_CLOUDFRONT_DISTRO_ID }}
